In [12]:
#import packages
import pandas as pd
import numpy as np
import sklearn

In [13]:
#pandas library reads csv data set file and stores it in the df DataFrame
df=pd.read_csv("wdbc.csv")

In [14]:
print(df.head())
print(df.info())

         ID Diagnosis  radius_1  texture_1  parameter_1  area_1  smoothness_1  \
0    842302         M     17.99      10.38       122.80  1001.0       0.11840
1    842517         M     20.57      17.77       132.90  1326.0       0.08474
2  84300903         M     19.69      21.25       130.00  1203.0       0.10960
3  84348301         M     11.42      20.38        77.58   386.1       0.14250
4  84358402         M     20.29      14.34       135.10  1297.0       0.10030

   compactness_1  concavity_1  concave points_1  ...  radius_3  texture_3  \
0        0.27760       0.3001           0.14710  ...     25.38      17.33
1        0.07864       0.0869           0.07017  ...     24.99      23.41
2        0.15990       0.1974           0.12790  ...     23.57      25.53
3        0.28390       0.2414           0.10520  ...     14.91      26.50
4        0.13280       0.1980           0.10430  ...     22.54      16.67

   parameter_3  area_3  smoothness_3  compactness_3  concavity_3  \
0       184.60  2019.0        0.1622         0.6656       0.7119
1       158.80  1956.0        0.1238         0.1866       0.2416
2       152.50  1709.0        0.1444         0.4245       0.4504
3        98.87   567.7        0.2098         0.8663       0.6869
4       152.20  1575.0        0.1374         0.2050       0.4000

   concave points_3  symmetry_3  fractal dimension_3
0            0.2654      0.4601              0.11890
1            0.1860      0.2750              0.08902
2            0.2430      0.3613              0.08758
3            0.2575      0.6638              0.17300
4            0.1625      0.2364              0.07678

[5 rows x 32 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   569 non-null    int64
 1   Diagnosis            569 non-null    object
 2   radius_1             569 non-null    float64
 3   texture_1            569 non-null    float64
 4   parameter_1          569 non-null    float64
 5   area_1               569 non-null    float64
 6   smoothness_1         569 non-null    float64
 7   compactness_1        569 non-null    float64
 8   concavity_1          569 non-null    float64
 9   concave points_1     569 non-null    float64
 10  symmetry_1           569 non-null    float64
 11  fractal dimension_1  569 non-null    float64
 12  radius_2             569 non-null    float64
 13  texture_2            569 non-null    float64
 14  parameter_2          569 non-null    float64
 15  area_2               569 non-null    float64
 16  smoothness_2         569 non-null    float64
 17  compactness_2        569 non-null    float64
 18  concavity_2          569 non-null    float64
 19  concave points_2     569 non-null    float64
 20  symmetry_2           569 non-null    float64
 21  fractal dimension_2  569 non-null    float64
 22  radius_3             569 non-null    float64
 23  texture_3            569 non-null    float64
 24  parameter_3          569 non-null    float64
 25  area_3               569 non-null    float64
 26  smoothness_3         569 non-null    float64
 27  compactness_3        569 non-null    float64
 28  concavity_3          569 non-null    float64
 29  concave points_3     569 non-null    float64
 30  symmetry_3           569 non-null    float64
 31  fractal dimension_3  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB
None

In [15]:
#number of columns (features), and rows (observations)
df.shape

(569, 32)

In [16]:
len(df)

569

In [17]:
#count, mean, standard deviation, minimum, quartiles, maximum
df.describe()

,ID,radius_1,texture_1,parameter_1,area_1,smoothness_1,compactness_1,concavity_1,concave points_1,symmetry_1,...,radius_3,texture_3,parameter_3,area_3,smoothness_3,compactness_3,concavity_3,concave points_3,symmetry_3,fractal dimension_3
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [18]:
df.describe(include=['object'])

       Diagnosis
count        569
unique         2
top            B
freq         357

In [19]:
#Check for missing data where False means no missing data
df.isnull()

,ID,Diagnosis,radius_1,texture_1,parameter_1,area_1,smoothness_1,compactness_1,concavity_1,concave points_1,...,radius_3,texture_3,parameter_3,area_3,smoothness_3,compactness_3,concavity_3,concave points_3,symmetry_3,fractal dimension_3
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
565,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
566,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
567,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
568,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [20]:
#Check for missing values
#Display total number of missing values (NaN)
df.isnull().sum().sum()

np.int64(0)

In [21]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
564    False
565    False
566    False
567    False
568    False
Length: 569, dtype: bool

In [23]:
#Need to convert diagnosis column to numbers
df2=df['Diagnosis']=df['Diagnosis'].replace({'M':0,'B':1})

C:\Users\laure\AppData\Local\Temp\ipykernel_43300\3618006910.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2=df['Diagnosis']=df['Diagnosis'].replace({'M':0,'B':1})

In [ ]:
#Standarize data
scaler= MinMaxScaler().fit(df)
df_scaled=scaler.transform(df)